### ISSUE TITLE
token should be secret

### ISSUE THREAD

**Issue by comet13579** [VincentChui2005/just-a-random-discord-bot#1]
Please fix your gitignore to hide your discord bot token
it is very safe :)

**Comment by eric15342335** [comment]
https://github.com/vinkami/just-a-random-discord-bot/blob/9d469a0dabff1bf1d256423e4e47c3b29aee66b9/.gitignore#L1

Maybe this is helpful:
[How do I make Git forget about a file that was tracked, but is now in .gitignore?](https://stackoverflow.com/q/1274057/14278613)

**Comment by vinkami** [comment]
That token is invalid. No action needed
